#!/usr/bin/env python3
"""
AI LLM SEO CRAWLER (single-file)

- Crawls a domain (breadth-first, same-host only, up to max_pages)
- Extracts: title, meta description, H1–H3, word count
- Sends extracted content to an LLM for:
  * SEO summary
  * Keyword suggestions
  * Content quality notes

Extensibility:
- Replace `call_llm()` with your own provider (OpenAI, local LLM, etc.)
- Add storage (SQLite/JSON/Elasticsearch) in `save_result()`
- Add robots.txt + sitemap parsing if needed
"""

import re
import time
import json
import queue
import urllib.parse as urlparse
from dataclasses import dataclass, asdict

import requests
from bs4 import BeautifulSoup

# -----------------------------
# Config
# -----------------------------

USER_AGENT = "AI-SEO-Crawler/1.0 (+https://example.com/bot)"
REQUEST_TIMEOUT = 10
CRAWL_DELAY_SEC = 1.0

MAX_PAGES = 30
ALLOWED_CONTENT_TYPES = ("text/html",)

# -----------------------------
# Data model
# -----------------------------

@dataclass
class PageSEOData:
    url: str
    status_code: int
    title: str
    meta_description: str
    h1: list
    h2: list
    h3: list
    word_count: int
    llm_summary: str
    llm_keywords: list
    llm_notes: str


# -----------------------------
# LLM integration (stub)
# -----------------------------

def call_llm(prompt: str) -> dict:
    """
    Replace this with your actual LLM call.
    Example: OpenAI, local HTTP endpoint, etc.

    Expected return format:
    {
        "summary": "...",
        "keywords": ["...", "..."],
        "notes": "..."
    }
    """
    # --- PLACEHOLDER IMPLEMENTATION ---
    # This is a dummy response so the script runs without an API key.
    # Wire your own LLM here.
    return {
        "summary": "Placeholder summary generated by a stub LLM.",
        "keywords": ["placeholder", "seo", "llm"],
        "notes": "Connect a real LLM endpoint in call_llm()."
    }

    # Example OpenAI-style pseudocode:
    # import openai
    # openai.api_key = "YOUR_KEY"
    # resp = openai.ChatCompletion.create(
    #     model="gpt-4o-mini",
    #     messages=[{"role": "user", "content": prompt}],
    #     temperature=0.3,
    # )
    # text = resp["choices"][0]["message"]["content"]
    # # parse text (e.g., JSON) and return dict


def build_llm_prompt(url: str, text: str, title: str, meta_desc: str) -> str:
    """
    Build a compact prompt for SEO analysis.
    """
    snippet = text[:4000]  # keep prompt size manageable
    return f"""
You are an SEO expert.

Analyze the following page and respond in strict JSON with keys:
"summary" (string),
"keywords" (array of strings),
"notes" (string).

URL: {url}
Title: {title}
Meta description: {meta_desc}

Content snippet:
\"\"\"{snippet}\"\"\"
"""


# -----------------------------
# HTML parsing
# -----------------------------

def extract_text(soup: BeautifulSoup) -> str:
    for tag in soup(["script", "style", "noscript"]):
        tag.decompose()
    text = soup.get_text(separator=" ")
    text = re.sub(r"\s+", " ", text).strip()
    return text


def parse_page(url: str, html: str, status_code: int) -> PageSEOData:
    soup = BeautifulSoup(html, "html.parser")

    title_tag = soup.find("title")
    title = title_tag.get_text(strip=True) if title_tag else ""

    meta_desc_tag = soup.find("meta", attrs={"name": "description"})
    meta_description = meta_desc_tag.get("content", "").strip() if meta_desc_tag else ""

    h1 = [h.get_text(strip=True) for h in soup.find_all("h1")]
    h2 = [h.get_text(strip=True) for h in soup.find_all("h2")]
    h3 = [h.get_text(strip=True) for h in soup.find_all("h3")]

    text = extract_text(soup)
    word_count = len(text.split())

    prompt = build_llm_prompt(url, text, title, meta_description)
    llm_resp = call_llm(prompt)

    return PageSEOData(
        url=url,
        status_code=status_code,
        title=title,
        meta_description=meta_description,
        h1=h1,
        h2=h2,
        h3=h3,
        word_count=word_count,
        llm_summary=llm_resp.get("summary", ""),
        llm_keywords=llm_resp.get("keywords", []),
        llm_notes=llm_resp.get("notes", ""),
    )


# -----------------------------
# Crawler core
# -----------------------------

def is_same_host(start_url: str, new_url: str) -> bool:
    a = urlparse.urlparse(start_url)
    b = urlparse.urlparse(new_url)
    return a.netloc == b.netloc


def normalize_url(base_url: str, link: str) -> str:
    link = link.strip()
    if not link:
        return ""
    abs_url = urlparse.urljoin(base_url, link)
    parsed = urlparse.urlparse(abs_url)
    if parsed.scheme not in ("http", "https"):
        return ""
    # remove fragments, normalize
    cleaned = parsed._replace(fragment="").geturl()
    return cleaned


def fetch_url(url: str) -> tuple[int, str, str]:
    headers = {"User-Agent": USER_AGENT}
    try:
        resp = requests.get(url, headers=headers, timeout=REQUEST_TIMEOUT)
    except requests.RequestException:
        return 0, "", ""

    content_type = resp.headers.get("Content-Type", "").split(";")[0].strip().lower()
    if content_type not in ALLOWED_CONTENT_TYPES:
        return resp.status_code, "", content_type

    return resp.status_code, resp.text, content_type


def extract_links(base_url: str, html: str) -> list:
    soup = BeautifulSoup(html, "html.parser")
    links = []
    for a in soup.find_all("a", href=True):
        norm = normalize_url(base_url, a["href"])
        if norm:
            links.append(norm)
    return links


def save_result(data: PageSEOData):
    """
    Persist or print results.
    For now, just print JSON to stdout.
    Replace with DB/file storage as needed.
    """
    print(json.dumps(asdict(data), ensure_ascii=False, indent=2))


def crawl(start_url: str, max_pages: int = MAX_PAGES):
    visited = set()
    q = queue.Queue()
    q.put(start_url)

    count = 0

    while not q.empty() and count < max_pages:
        url = q.get()
        if url in visited:
            continue
        visited.add(url)

        print(f"\n[CRAWL] Fetching: {url}")
        status_code, html, content_type = fetch_url(url)
        print(f"[CRAWL] Status: {status_code}, Content-Type: {content_type}")

        if status_code != 200 or not html:
            continue

        # Parse + LLM SEO analysis
        data = parse_page(url, html, status_code)
        save_result(data)

        # Extract internal links
        for link in extract_links(url, html):
            if is_same_host(start_url, link) and link not in visited:
                q.put(link)

        count += 1
        time.sleep(CRAWL_DELAY_SEC)


# -----------------------------
# Entry point
# -----------------------------

if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python seo_crawler.py https://example.com [max_pages]")
        sys.exit(1)

    start_url = sys.argv[1]
    max_pages = int(sys.argv[2]) if len(sys.argv) >= 3 else MAX_PAGES

    crawl(start_url, max_pages)
